swagger: "2.0"
info:
  title: "Aplicacion web para reserva de peliculas"
  description: "Esta documentación se refiere a un sistema de reserva de peliculas"
  version: "1.0.0"
host: "movies.swagger.io"
basePath: "/v1"
#Tags para filtrar el swagger
tags:
- name: "administrador"
  description: "Operaciones de vendedores"
- name: "clientes"
  description: "Operaciones de clientes"
- name: "reservas"
  description: "Operaciones de eventos"
- name: "peliculas"
  description: "Operaciones de compras"
